### PR TITLE
Run the Linux CI with -DLLVM_ENABLE_WERROR:BOOL=ON

### PR DESCRIPTION
**Pull request by svs-quic**
This will help us catch issues in the PR earlier.

### CODE REVIEW

**Comment by svs-quic** [comment]
The initial commit failed with the following error that was fixed in #873. Capturing it here to highlight the kind of issues we can catch by enabling WERROR.

https://github.com/qualcomm/eld/actions/runs/22436839871/job/64968756311?pr=875

```
../llvm-project/llvm/tools/eld/test/Common/Plugin/PluginActivityLogFile/PluginActivityLogPlugin.cpp:69:18: error: 'removeSymbolTableEntry' is deprecated [-Werror,-Wdeprecated-declarations]
   69 |     getLinker()->removeSymbolTableEntry(expBazSymbol.value());
      |                  ^
../llvm-project/llvm/tools/eld/include/eld/PluginAPI/LinkerWrapper.h:598:3: note: 'removeSymbolTableEntry' has been explicitly marked deprecated here
  598 |   DEPRECATED void removeSymbolTableEntry(plugin::Symbol S);
      |   ^
../llvm-project/llvm/tools/eld/include/eld/PluginAPI/Defines.h:33:35: note: expanded from macro 'DEPRECATED'
   33 | #define DEPRECATED __attribute__((deprecated))
      |                                   ^
1 error generated.
```

**Comment by quic-seaswara** [comment]
LLVM does not have this policy to gate checkins, I prefer this be done in the nightly as a seperate workflow to alert developers about -Werror.
